mail:
  debug: true
upload:
  path: /home/old_robot/Downloads/sweater/uploads
server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    username: 
    password: 
    port: 465
    protocol: smtps
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:54321/sweater
    username: postgres
    password: asdasd123
  freemarker:
    expose-request-attributes: true
