mail:
  debug: true
upload:
  path: ${SWEATER_UPLOAD_PATH}
server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_LOGIN}
    password: ${EMAIL_PASSWORD}
    port: 465
    protocol: smtps
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto:  create
    database: postgresql
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:54321/sweater
    username: postgres
    password: asdasd123
  freemarker:
    expose-request-attributes: true
